server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework: ERROR
    com.example.demo: INFO
  file:
    path: log/spring-boot.log
  logback:
    rollingpolicy:
      max-file-size: "10MB"
      max-history: 10
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"
      clean-history-on-start: true
#  pattern:
#    console: "%d{yyyy-MM-dd hh-mm-ss.SSS} %-5level [%thread]  %logger[%method:%line] - %msg%n"
#    file: "%d{yyyy-MM-dd hh-mm-ss.SSS} %-5level [%thread]  %logger[%method:%line] - %msg%n"

spring:
  application:
    name: SpringBootJdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver                                 # "com.mysql.jdbc.Driver" is deprecated.
    url: jdbc:mysql://192.168.219.196/mysql?autoReconnect=true&userSSL=false    # jdbc:mysql://localhost/{database_name}?autoReconnect=true&userSSL=false
    username: root
    password: root

security:
  token-expiration-minute: 10
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 80

